version: "2"

services:
  ttt_sync:
    image: kimbtechnologies/ttt_sync:latest
    restart: always
    container_name: ttt_sync
    ports:
      - "8080:80"
    volumes:
      - ./data/:/php-code/data/
    environment:
      - DEVMODE=false
      - CONF_DOMAIN=http://localhost:8080/
      - CONF_TIMEZONE=Europe/Berlin # php timezone string
      #- CONF_IMPRESSUMURL=http://example.com/impressum # imprint/ privacy link and name pf link (optional)
      #- CONF_IMPRESSUMNAME=Imprint and Privacy
      - ADMIN_ACCOUNT=test # admin account (initial creation on docker container startup)
      - ADMIN_PASSWORD=
